version: '2'

networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge

services:
  janus:
    image: mcroth/docker-janus:latest 
    container_name: janus-gateway
    volumes:
      - ./janus/etc/janus/:/opt/janus/etc/janus/
      - ./janus/janus.log:/var/log/janus.log
    ports:
      - 8088:8088
      - 8188:8188
    networks:
      - back-tier
      - front-tier
  web:
    build: ./nginx/
    container_name: janus-web
    networks:
      - front-tier
    ports:
      - 80:80
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/conf.d:/etc/nginx/conf.d
